Catch build failures not to fail job

diff --git a/.github/workflows/cmsis_rv2.yml b/.github/workflows/cmsis_rv2.yml
--- a/.github/workflows/cmsis_rv2.yml
+++ b/.github/workflows/cmsis_rv2.yml
@@ -82,7 +82,7 @@ jobs:
       working-directory: Project
       run: |
         export PATH=$PATH:/opt/VHT
-        python build.py --verbose build run
+        python build.py --verbose build run || echo "Something failed!"
 
     - name: Archive results
       uses: actions/upload-artifact@v2
